---

- name: Template passwords
  template:
    src: passwords.yml
    dest: "{{ openhpc_passwords_output_path }}"
  delegate_to: localhost
  run_once: true

- name:  Template k3s token to terraform
  template:
    src: k3s-token.auto.tfvars.json.j2
    dest: "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/terraform/k3s-token.auto.tfvars.json"
  delegate_to: localhost
  run_once: true
