---

- name: Template passwords
  template:
    src: passwords.yml
    dest: "{{ openhpc_passwords_output_path }}"
  delegate_to: localhost
  run_once: true

- name: Generate k3s token
  ansible.builtin.set_fact:
    k3s_token_secret: ""

- name:  Generate k3s token and add to terraform
  vars:
    token: "{{ lookup('ansible.builtin.password', '/dev/null', length=64) }}"
  replace:
    path: "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/terraform/variables.tf"
    regexp: "k3s_token_replace_me"
    replace: "{{ token }}"


# - name: Ensure munge key directory exists
#   file:
#     state: directory
#     recurse: true
#     path: "{{ openhpc_passwords_mungekey_output_path | dirname }}"

# - name: Create a munge key
#   copy:
#     content:  "{{ lookup('password', '/dev/null chars=ascii_letters,digits,hexdigits,punctuation') }}"
#     dest: "{{ openhpc_passwords_mungekey_output_path }}"
#     force: false
