- hosts: all
  become: no
  gather_facts: no
  tags:
    - reimage_login
    - reimage_compute
    - reimage_control
  tasks:
    - import_tasks: get_image_ids.yml

- name: Reimage login nodes via rebuild adhoc
  tags: reimage_login
  import_playbook: ../adhoc/rebuild.yml
  vars:
    rebuild_image: "{{ login_build.artifact_id }}"
    rebuild_hosts: login

- hosts: login
  become: no
  gather_facts: no
  tags: reimage_login
  tasks:
    - name: Check slurm up after reimaging login node
      import_tasks: "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/hooks/check_slurm.yml"

- name: Reimage compute nodes via rebuild adhoc - this sets metadata
  tags: reimage_compute
  import_playbook: ../adhoc/rebuild.yml
  vars:
    rebuild_image: "{{ compute_build.artifact_id }}"
    rebuild_hosts: compute

- hosts: login
  become: no
  gather_facts: no
  tags: reimage_compute
  tasks:
    - name: Check compute node rebuild completed
      shell:
        cmd: openstack server show {{ item }} --format value -c image
      register: openstack_compute
      delegate_to: localhost
      loop: "{{ groups['compute'] }}"
      retries: 5
      delay: 30
      until: compute_build.artifact_id in openstack_compute.stdout
      changed_when: false
    
    - name: Check slurm up after reimaging compute nodes
      import_tasks: "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/hooks/check_slurm.yml"
    
    # TODO: This is specific to smslabs/arcus environment config - could generalise to all compute nodes
    - name: Request compute node rebuild via Slurm
      shell:
        cmd: scontrol reboot ASAP nextstate=RESUME reason='rebuild image:{{ compute_build.artifact_id }}' {{ openhpc_cluster_name }}-compute-[0-1]
      become: yes
        
    - name: Check compute node rebuild completed
      shell:
        cmd: openstack server show {{ item }} --format value -c image
      register: openstack_compute
      delegate_to: localhost
      loop: "{{ groups['compute'] }}"
      retries: 5
      delay: 30
      until: compute_build.artifact_id in openstack_compute.stdout
      changed_when: false

- hosts: compute
  become: no
  gather_facts: no
  tags: reimage_compute
  tasks:
    - name: Wait for compute connection
      wait_for_connection:
        timeout: 800
        delay: 5
      register: compute_connect
      retries: 3
      delay: 10
      until: compute_connect is not failed
    
    - name: Check slurm up after reimaging compute nodes
      import_tasks: "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/hooks/check_slurm.yml"
      run_once: true

- name: Reimage control nodes via rebuild adhoc
  tags: reimage_control
  import_playbook: ../adhoc/rebuild.yml
  vars:
    rebuild_image: "{{ control_build.artifact_id }}"
    rebuild_hosts: control

- name: Run slurm playbook again to add partition info
  import_playbook: ../slurm.yml
  tags: reimage_control

- hosts: control
  become: no
  gather_facts: no
  tags: reimage_control
  tasks:
    - name: Check slurm up after reimaging login node
      import_tasks: "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/hooks/check_slurm.yml"
