- hosts: control
  name: Create IMB pingpong sbatch script
  tags: pingpong
  gather_facts: false
  tasks:
  - name: Create directory on shared filesystem
    file:
      path: /home/tests
      state: directory
      owner: centos
      group: centos
    become: true
  - name: Create sbatch script
    copy:
      dest: "/home/tests/pingpong.sh"
      content: |
        #!/usr/bin/bash

        #SBATCH --ntasks=2
        #SBATCH --ntasks-per-node=1
        #SBATCH --exclusive
        
        echo SLURM_JOB_NODELIST: $SLURM_JOB_NODELIST
        module load gnu9
        module load openmpi4
        module load imb

        mpirun IMB-MPI1 pingpong
