- name: set cluster root password
  hosts: all
  tags: root_pass_cli
  become: true
  tasks:
    - name: include root if called
      include_role:
        name: root_pass_cli
      when: new_root_pass is defined

- name: Ensure yum repos are local
  hosts: all
  tags: ansible_yum_config
  become: true
  tasks:
    - include_role:
        name: ansible_yum_config

- name: nrel-proto fixes - compute nodes
  hosts: compute
  become: true
  tasks:
    - name: Create scratch directory - should be on local SSD on real cluster
      file:
        path: /tmp/scratch
        state: directory

- name: Ensure times are correct
  hosts: all
  tags: set_time_on_servers
  become: true
  tasks:
    - include_role:
        name: ansible-role-ntp
    - shell: "echo '{{distro_releasever}}' > /etc/yum/vars/releasever"
      tags: lock_releasever

- name: set hostname to hpc.nrel.gov domain
  hosts: control,login
  tags: set_hpc_hostname
  become: true
  tasks:
    - include_role:
        name: ansible-role-ntp
    - shell: "hostnamectl set-hostname {{ ansible_hostname }}.hpc.nrel.gov"

- name: install ldap requirements to nodes
  hosts: compute
  tags: vermilion_ldap_client
  become: true
  tasks:
    - include_role:
        name: vermilion_ldap_client


    # # - block:
    #   # - name: Add Ceph reposity
    #   #   yum_repository: centos-release-ceph
    #   #     name: "centos-release-ceph-{{ os_manila_mount_ceph_version }}"
    #   #     description: CentOS Storage SIG repo for ceph
    #   #     baseurl: "{{ os_manila_mount_ceph_repo_base }}"
    #   #     gpgkey: "{{ os_manila_mount_ceph_repo_key | default(omit) }}"
    # - name: NREL says - Install epel and ceph yum repo
    #   yum:
    #     name:
    #       - epel-release
    #       - "centos-release-ceph-{{ os_manila_mount_ceph_version }}"

    # - name: Install relevant yum packages
    #   yum:
    #     name:
    #       - ceph-common
    # # when:
    # #   - (ansible_os_family == 'RedHat') or (ansible_os_family == 'Rocky')
    # #   - os_manila_mount_pkgs_install | default(true) | bool

