# - name: " "
#   hosts: control,login,compute
#   tags: nrel_
#   become: true
#   tasks:
#     - include_role:
#         name:

# - name: "Set releasever and local repos"
#   hosts: all
#   tags: nrel_releasever
#   become: true
#   tasks:
#     - include_role:
#         name: releasever-config

- name: "fix possibly bad repo pointers"
  hosts: all
  tags:
    - vs_pre
    - nrel_repofix
  become: true
  tasks:
    - shell:
        cmd: for FF in `ls /etc/yum.repos.d/Rocky*`; do sed -i 's#gov/rocky/#gov/rocky-vault/#g' $FF; done

    - name: "change root password"
      user:
        name: root
        update_password: always
        password: "{{ vault_vs_root_pass|password_hash('sha256') }}"

- name: NREL pre - Ensure times are correct
  hosts: all
  tags:
    - vs_pre
    - set_time_on_servers
  become: true
  tasks:
    - name: Set timezone to Americas/Denver
      timezone:
        name: America/Denver
    - include_role:
        name: aco.core.ntp

# This may be unnecessary now.
# # Stupid dependency hack
# - name: NREL PRE - re-install libibverbs openmpi
#   hosts: all
#   tags:
#     - vs_pre
#     - dependency_dnf_hack
#   become: true
#   vars:
#     rm_packages:
#       - libibverbs
#       - openmpi

#     packages:
#       - autoconf
#       - automake
#       - binutils
#       - bison
#       - byacc
#       - ctags
#       - diffstat
#       - gcc
#       - gcc-c++
#       - gdb
#       - glibc-devel
#       - ltrace
#       - make
#       - patchutils
#       - strace
#       - vim
#       - nano
#       # policycoreutils-python-utils setools-console setroubleshoot
#   tasks:
#     - name: rm problem packages
#       dnf:
#         name: "{{rm_packages}}"
#         state: absent
#         allowerasing: true
#     - name: Add useful packages
#       dnf:
#         name: "{{packages}}"
#         state: present
#         nobest: true

# - name: "NREL PRE - dnf packages"
#   hosts: all
#   tags: dnf_initial_update
#   become: true
#   tasks:
#     - lineinfile:
#         path: /etc/yum.repos.d/cuda-rhel8.repo
#         regexp: '^enabled'
#         line: enabled=0

#     - name: dnf fix challenging dependency issues
#       dnf:
#         name: "*"
#         nobest: true
#         allowerasing: true
#         skip_broken: true

# - name: "NREL pre - set cluster root password"
#   hosts: all
#   tags: root_pass_cli
#   become: true
#   tasks:
#     - name: include root if called
#       include_role:
#         name: root_pass_cli
#       when: new_root_pass is defined

# - name: "NREL pre - set admin hostnames to hpc.nrel.gov domain"
#   hosts: control,login
#   tags: set_hpc_hostname
#   become: true
#   tasks:
#     - shell: "hostnamectl set-hostname {{ ansible_hostname }}.hpc.nrel.gov"


# Builds the /etc/hosts inventory files.
- name: nrel-proto fixes - workaround no internal DNS
  hosts:
    - cluster
  become: true
  tags:
    - vs_pre
    - etc_hosts
  tasks:
    - name: Internal DNS workaround - generate /etc/hosts file content
      # which interface is used as ansible_host is defined by terraform (see `access_network`) so this is deterministic for multi-rail hosts
      set_fact:
        etc_hosts_content: |
          {% for host in groups['cluster'] %}{{ hostvars[host]['ansible_host'] }} {{ host }}.novalocal {{ host }}
          {% endfor %}
      run_once: true

    - name: Internal DNS workaround  - create entries in /etc/hosts for all nodes
      blockinfile:
        path: /etc/hosts
        create: yes
        state: present
        block: "{{ hostvars[ansible_play_hosts[0]].etc_hosts_content }}"

# This may be fixed now
# # ref: Error: cannot setup namespace using "/usr/bin/newuidmap": should have setuid or have filecaps setuid:
# - name: "podman uid-gid workaround"
#   hosts:
#     - cluster
#   become: true
#   tags:
#     - vs_pre
#     - uid_gid_hack
#   tasks:
#     - name: "set newuidmap/newgidmap perms so containers will start"
#       file:
#         path: "{{ item }}"
#         mode: '4755'
#       loop:
#         - /usr/bin/newgidmap
#         - /usr/bin/newuidmap

- name: "NREL pre - install ldap requirements to nodes"
  hosts: compute
  tags:
    - vs_pre
    - vermilion_ldap_client
  become: true
  tasks:
    - include_role:
        name: vermilion_ldap_client


# TODO: KBENDL - check compatibility with new playbook
- name: "NREL pre - Mount cephfs volumes"
  hosts: all
  tags:
    - vs_pre
    - aco.core.cephfs
  become: true
  tasks:
    - include_role:
        name: aco.core.cephfs
      tags:
        - aco.core.cephfs

# TODO - get latest playbook
# - name: Ensure yum repos are local
#   hosts: all
#   tags: ansible_yum_config
#   become: true
#   tasks:
#     - include_role:
#         name: ansible_yum_config
