- name: Create Terraform plan
  community.general.terraform:
    project_path: "{{ tf_project_path }}"
    state: planned
    plan_file: tf.plan
    force_init: yes
  register: _tf_plan

- name: Show Terraform plan
  debug:
    msg: "{{ _tf_plan.stdout }}"

- name: Confirm Terraform plan execution
  pause:
    prompt: "Do you want to execute this plan? (Only 'yes' executes)"
  register: confirm_plan
  when: "'No changes. Your infrastructure matches the configuration.' not in _tf_plan.stdout"
  # TODO: add override for autodeployment, e.g. CI!

- name: Execute Terraform plan
  community.general.terraform:
    project_path: "{{ tf_project_path }}"
    state: "{{ tf_state }}"
    plan_file: tf.plan
    force_init: yes
  when:
    - not confirm_plan.skipped | default(false)
    - confirm_plan.user_input | bool
  register: _tf_apply
  # TODO: add override for autodeployment, e.g. CI!

- debug:
    msg: "{{ _tf_apply.stdout }}"
  when: "'stdout' in _tf_apply"