---

# The chart to use
kube_prometheus_stack_chart_repo: https://prometheus-community.github.io/helm-charts
kube_prometheus_stack_chart_name: kube-prometheus-stack
kube_prometheus_stack_chart_version: 59.1.0

# Release information
kube_prometheus_stack_release_namespace: monitoring-system
kube_prometheus_stack_release_name: kube-prometheus-stack

# The timeout to wait for the release to become ready
kube_prometheus_stack_wait_timeout: 5m

login_ip: "{{ hostvars[groups['openondemand'][0]]['ansible_host'] }}" # probably needs to be more robust
control_ip: "{{ ansible_default_ipv4.address| default(ansible_all_ipv4_addresses[0]) }}"
control_sslip: "{{ control_ip | regex_replace('\\.', '-') }}.sslip.io" 

grafana_volume_size: 10Gi

grafana_auth_anonymous: false

slack_integration:
  channel: "#alerts"
  app_creds: # TODO: need to find best way to build this into secrets store as must be manually retrieved from app

alertmanager_config:
  route:
    group_by: ['...']
  receivers:
    - name: 'null'

alertmanager_replicas: 1

# Must be within K3s' reserved port range (default 30000-32767)
prometheus_port: 30000
grafana_port: 30001
alertmanager_port: 30002

prometheus_image_tag: "v2.27.0"

prometheus_db_dir: "/var/lib/prometheus"

prometheus_storage_retention: "30d"
# Available since Prometheus 2.7.0
# [EXPERIMENTAL] Maximum number of bytes that can be stored for blocks. Units
# supported: KB, MB, GB, TB, PB.
prometheus_storage_retention_size: "40GB"

prometheus_volume_size: 40Gi

prometheus_alert_relabel_configs: []

prometheus_global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 15s

prometheus_external_labels:
  environment: "{{ ansible_fqdn | default(inventory_hostname) | default(ansible_host) }}"

prometheus_scrape_configs: []

prometheus_extra_rules: []

prometheus_rules:
  appliance-rules:
    groups:
    - name: all
      rules: "{{ prometheus_extra_rules }}" 

# ------------------------------------------------------------------------------------------
grafana_image_tag: 11.2.2

grafana_data_dir: "/var/lib/grafana"

grafana_security:
  admin_user: grafana
  admin_password: "{{ vault_grafana_admin_password }}"

# see https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml for configuration options
grafana_auth: {}
grafana_ldap: {}

#######
# Plugins from https://grafana.com/plugins
grafana_plugins: []

# Additional datasources to configure alongside kube-prometheus-stack defaults
grafana_datasources: []

alertmanager_image_tag: v0.27.0

node_exporter_image_tag: v1.8.2

