general_v1_small:
  image: ohpc-compute-210909-1316.qcow2
  flavor: general.v1.small
  keypair: centos-at-steveb-ansible
  network: stackhpc-ipv4-geneve

general_v1_medium:
  image: ohpc-compute-210909-1316.qcow2
  flavor: general.v1.medium
  keypair: centos-at-steveb-ansible
  network: stackhpc-ipv4-geneve


openhpc_ram_multiplier: 0.90 # TODO: fixme for groups
openhpc_slurm_partitions:
- name: small
  default: yes
  cloud_nodes: dev-small-[2-3]
  cloud_instances: "{{ general_v1_small }}"

  # groups:   # TODO: support this
  #   - name: small
  #   - name: small_cloud
  #     ram_multiplier: 0.90
  #     cloud_nodes: dev-small-[2-3]
  #     cloud_instances: "{{ general_v1_small }}"

- name: burst
  default: no
  cloud_nodes: 'burst-[0-3]'
  cloud_instances: "{{ general_v1_medium }}"

