cloud_spec:
  image: ohpc-compute-210909-1316.qcow2
  flavor: general.v1.small
  keypair: centos-at-steveb-ansible
  network: stackhpc-ipv4-geneve

openhpc_slurm_partitions:
- name: small
  default: yes
  cloud_nodes: '-[2-3]'
  cloud_features: "{{ cloud_spec }}"

- name: burst
  default: no
  groups:
  - name: smallmem
    cloud_nodes: '[0-3]'
    cloud_features: "{{ cloud_spec }}"
    ram_mb: 9996
    cpus: 2
  - name: bigmem
    cloud_nodes: '[4-6]'
    cloud_features: "{{ cloud_spec }}"
    ram_mb: 9992
    cpus: 2
    
