---
roles:
  - src: stackhpc.nfs
  - src: stackhpc.openhpc
  - src: cloudalchemy.node_exporter
  - src: cloudalchemy.blackbox-exporter
  - src: cloudalchemy.prometheus
  - src: cloudalchemy.alertmanager
  - src: cloudalchemy.grafana
  - src: geerlingguy.mysql
  - src: https://github.com/stackhpc/ansible_role_spack
    name: stackhpc.spack
    version: HEAD
  - src: jriguera.configdrive

  # - name: stig-hardening
  #   src: git+git@github.nrel.gov:hpc/stig-hardening.git
  #   version: v0.0.2


collections:
- name: containers.podman
- name: community.grafana
- name: https://github.com/stackhpc/ansible_collection_slurm_openstack_tools
  type: git
  version: main
...
