---
roles:
  - src: stackhpc.nfs
  - src: https://github.com/stackhpc/ansible-role-openhpc
    # https://github.com/stackhpc/ansible-role-openhpc
    # git+git@github.nrel.gov:hpc/sync_slurm_allocations.git
    version: feature/StateSaveLocation
    name: stackhpc.openhpc
  - src: cloudalchemy.node_exporter
  - src: cloudalchemy.blackbox-exporter
  - src: cloudalchemy.prometheus
  - src: cloudalchemy.alertmanager
  - src: cloudalchemy.grafana
  - src: geerlingguy.mysql
  - src: jriguera.configdrive
  - src: git+https://github.com/openstack/ansible-hardening

collections:
- name: containers.podman
- name: community.grafana
- name: https://github.com/stackhpc/ansible_collection_slurm_openstack_tools
  type: git
  version: main
- name: freeipa.ansible_freeipa
...
