---
roles:
  - src: stackhpc.nfs
  - src: stackhpc.openhpc
  - src: cloudalchemy.node_exporter
  - src: cloudalchemy.blackbox-exporter
  - src: https://github.com/dmrub/ansible-prometheus # Can be reverted once https://github.com/cloudalchemy/ansible-prometheus/pull/366 merged
    name: cloudalchemy.prometheus
  - src: cloudalchemy.alertmanager
  - src: cloudalchemy.grafana
  - src: geerlingguy.mysql
  - src: jriguera.configdrive

collections:
- name: containers.podman
- name: community.grafana
- name: https://github.com/stackhpc/ansible_collection_slurm_openstack_tools
  type: git
  version: main
...
