---
roles:
  - src: stackhpc.nfs
  - src: https://github.com/stackhpc/ansible-role-openhpc
    version: feature/StateSaveLocation # also includes feature/flexi-config
    name: stackhpc.openhpc
  - src: cloudalchemy.node_exporter
  - src: cloudalchemy.blackbox-exporter
  - src: cloudalchemy.prometheus
  - src: cloudalchemy.alertmanager
  - src: cloudalchemy.grafana
  - src: geerlingguy.mysql
  - src: jriguera.configdrive

collections:
- name: containers.podman
- name: community.grafana
- name: https://github.com/stackhpc/ansible_collection_slurm_openstack_tools
  type: git
  version: main
...
