---
roles:
  - src: https://github.com/stackhpc/ansible-role-ofed
    name: stackhpc.ofed
  - src: https://github.com/stackhpc/ansible-role-cluster-nfs.git
    name: stackhpc.nfs
    version: feature/rdma
  - src: https://github.com/stackhpc/ansible-role-openhpc
    name: stackhpc.openhpc
  - src: cloudalchemy.node_exporter
  - src: cloudalchemy.blackbox-exporter
  - src: https://github.com/dmrub/ansible-prometheus # Can be reverted once https://github.com/cloudalchemy/ansible-prometheus/pull/366 merged
    name: cloudalchemy.prometheus
  - src: cloudalchemy.alertmanager
  - src: cloudalchemy.grafana
  - src: geerlingguy.mysql
  - src: jriguera.configdrive
  - src: https://github.com/stackhpc/ood-ansible.git
    name: osc.ood
    version: feature/Rocky

collections:
- name: containers.podman
- name: community.grafana
- name: https://github.com/stackhpc/ansible_collection_slurm_openstack_tools
  type: git
  version: main
...
