---
roles:
  - src: stackhpc.nfs
  - name: stackhpc.openhpc
    src: https://github.com/stackhpc/ansible-role-openhpc
    version: e3a9d3ed4b34243ea75f31a285cca792a43ca4a0
  - src: cloudalchemy.node_exporter
  - src: cloudalchemy.blackbox-exporter
  - src: cloudalchemy.prometheus
  - src: cloudalchemy.alertmanager
  - src: cloudalchemy.grafana
  - src: geerlingguy.mysql
  - src: https://github.com/stackhpc/ansible_role_spack
    name: stackhpc.spack
    version: HEAD
  - src: jriguera.configdrive
  - name: sync_slurm_allocations
    src: git+git@github.nrel.gov:hpc/sync_slurm_allocations.git
    type: git
    version: feature/port_from_eagle_to_generic
  - name: cluster_config_manager
    src: git+git@github.nrel.gov:hpc/cluster_config_manager.git
    type: git
    version: feature/galaxy-role-install
  - name: cluster_dataset_manager
    src: git+git@github.nrel.gov:hpc/cluster_dataset_manager.git
    type: git
    version: feature/generic_for_vermilion
  - name: pam_mkhomedir_plus
    src: git+git@github.nrel.gov:hpc/pam_mkhomedir_plus.git
    type: git
    version: feature/ansible-galaxy
  - name: slurm_lex_accounting
    src: git+git@github.nrel.gov:hpc/slurm_lex_accounting.git
    type: git
    version: feature/ansible-galaxy
  - name: vstack_admin_config
    src: git+git@github.nrel.gov:hpc/vstack_admin_config.git
    type: git
  - name: vstack_common_config
    src: git+git@github.nrel.gov:hpc/vstack_common_config.git
    type: git

  # - name: stig-hardening
  #   src: git+git@github.nrel.gov:hpc/stig-hardening.git
  #   version: v0.0.2


collections:
- name: containers.podman
- name: community.grafana
- name: https://github.com/stackhpc/ansible_collection_slurm_openstack_tools
  type: git
  version: main
- name: openstack.cloud
...
