---
roles:
  - src: stackhpc.nfs
  - src: stackhpc.openhpc
  - src: cloudalchemy.node-exporter
  - src: cloudalchemy.blackbox-exporter
  - src: cloudalchemy.prometheus
  - src: cloudalchemy.alertmanager
  - src: cloudalchemy.grafana
  - src: geerlingguy.mysql
  - src: git@github.com:stackhpc/ansible_role_spack.git
    name: stackhpc.spack
    version: HEAD

collections:
- name: containers.podman
- name: community.grafana
- name: https://github.com/stackhpc/ansible_collection_slurm_openstack_tools
  type: git
  version: main
...
