- name: nrel-proto fixes - workaround no internal DNS
  hosts:
    - cluster
  become: true
  gather_facts: false
  tags: etc_hosts
  tasks:
    - name: Internal DNS workaround - generate /etc/hosts file content
      # which interface is used as ansible_host is defined by terraform (see `access_network`) so this is deterministic for multi-rail hosts
      set_fact:
        etc_hosts_content: |
          {% for host in (groups['cluster'] | difference(groups['builder'])) %}{{ hostvars[host]['ansible_host'] }} {{ host }}.novalocal {{ host }}
          {% endfor %}
      run_once: true
    - name: Internal DNS workaround  - create entries in /etc/hosts for all nodes
      blockinfile:
        path: /etc/hosts
        create: yes
        state: present
        block: "{{ hostvars[ansible_play_hosts[0]].etc_hosts_content }}"

- name: nrel-proto fixes - remove multiple routes
  hosts:
    - cluster
  become: true
  gather_facts: false
  tags: routes
  tasks:
    - name: Get default routes
      shell:
        cmd: "ip route | grep default"
      register: ip_route_show
      changed_when: false
    - name: Delete uneeded defaults
      command:
        cmd: "ip route del {{ item }}"
      loop: "{{ ip_route_show.stdout_lines }}"
      when: "'default via 192.68.67.1' not in item"
    - name: Restart NetworkManager # this replaces the deleted default route in the packer VM
      systemd:
        state: restarted
        name: NetworkManager.service

- name: nrel-proto fixes - compute nodes
  hosts: compute
  become: true
  gather_facts: false
  tasks:
    - name: Create scratch directory - should be on local SSD on real cluster
      file:
        path: /tmp/scratch
        state: directory

