- hosts: localhost
  name: Create users on deploy host as jumphost
  become: yes
  tasks:
    - import_tasks: users.yml

- hosts: control
  name: Create users on control + homedirectories & ssh keys
  become: yes
  tasks:
    - import_tasks: users.yml

- hosts:
    - login
    - compute
  name: Create users on other Slurm nodes
  become: yes
  tasks:
    - import_tasks: users.yml
