- name: nrel-proto fixes - all nodes
  hosts: cluster
  become: true
  tasks:
    - name: Internal DNS workaround - generate /etc/hosts file content
      set_fact: # TODO: define which network to use below:
        etc_hosts_content: |
          {% for host in ansible_play_hosts %}{{ hostvars[host]['ansible_default_ipv4']['address'] }} {{ host }}.novalocal {{ host }}
          {% endfor %}
      run_once: true
    - name: Internal DNS workaround  - create entries in /etc/hosts for all nodes
      blockinfile:
        path: /etc/hosts
        create: no # TODO: ??
        state: present
        block: "{{ hostvars[ansible_play_hosts[0]].etc_hosts_content }}"

- name: nrel-proto fixes - compute nodes
  hosts: compute
  become: true
  tasks:
    - name: Create scratch directory - should be on local SSD on real cluster
      file:
        path: /tmp/scratch
        state: directory
    - name: Check hyperthreading
      command: "cat /sys/devices/system/cpu/smt/control"
      register: smt
      changed_when: false
    - name: Turn off hyperthreading to give consistent core count (else nodes get downed by Slurm) # some have it on, some have it off
      shell: echo off > /sys/devices/system/cpu/smt/control
      when: "smt.stdout != 'off'"
    - name: rerun facts
      setup:
    
    # - name: Check processor count for compute nodes
    #   set_fact:
    #     pre_total_cores: "{{ dict(groups['compute'] | zip(groups['compute'] | map('extract', hostvars) | map(attribute='ansible_processor_vcpus') )) }}"
    #   run_once: true
    
    # - assert:
    #     that: pre_total_cores | unique | length == 1
    #     fail_msg: "Different numbers of cores in 'compute' nodes:\n{{ pre_total_cores | to_nice_yaml }}"
    #     success_msg: "Core counts ok"
    #   run_once: true
