- name: Create /etc/hosts
  hosts: cluster
  become: true
  tasks:
    
    - name: Internal DNS workaround - generate /etc/hosts file content
      set_fact: # TODO: define which network to use below:
        etc_hosts_content: |
          {% for host in ansible_play_hosts %}{{ hostvars[host]['ansible_default_ipv4']['address'] }} {{ host }}.novalocal {{ host }}
          {% endfor %}
      run_once: true
    - name: Internal DNS workaround  - create entries in /etc/hosts for all nodes
      blockinfile:
        path: /etc/hosts
        create: no # TODO: ??
        state: present
        block: "{{ hostvars[ansible_play_hosts[0]].etc_hosts_content }}"
