- name: Drivers for baremetal SMS labs nodes
  hosts: cluster
  become: true
  tags: drivers
  tasks:
    - name: Add elrepo repository
      yum_repository:
        name: elrepo
        description: ELRepo.org Community Enterprise Linux Repository - el8
        baseurl:
          - http://elrepo.org/linux/elrepo/el8/$basearch/
          - http://mirrors.coreix.net/elrepo/elrepo/el8/$basearch/
          - http://mirror.rackspace.com/elrepo/elrepo/el8/$basearch/
          - http://linux-mirrors.fnal.gov/linux/elrepo/elrepo/el8/$basearch/
        mirrorlist: http://mirrors.elrepo.org/mirrors-elrepo.el8
        enabled: yes
        gpgcheck: yes
        gpgkey: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
    - name: Add HPE Emulex drivers
      yum:
        name: kmod-be2net

- name: Workaround no internal DNS
  hosts: cluster
  become: true
  tags: etc_hosts
  tasks:
    - name: Internal DNS workaround - generate /etc/hosts file content
      set_fact: # TODO: define which network to use below:
        etc_hosts_content: |
          {% for host in ansible_play_hosts %}{{ hostvars[host]['ansible_default_ipv4']['address'] }} {{ host }}.novalocal {{ host }}
          {% endfor %}
      run_once: true
    - name: Internal DNS workaround  - create entries in /etc/hosts for all nodes
      blockinfile:
        path: /etc/hosts
        create: no # TODO: ??
        state: present
        block: "{{ hostvars[ansible_play_hosts[0]].etc_hosts_content }}"

- name: nrel-proto fixes - compute nodes
  hosts: compute
  become: true
  tasks:
    - name: Create scratch directory - should be on local SSD on real cluster
      file:
        path: /tmp/scratch
        state: directory
    - name: Check hyperthreading
      command: "cat /sys/devices/system/cpu/smt/control"
      register: smt
      changed_when: false
    - name: Turn off hyperthreading to give consistent core count (else nodes get downed by Slurm) # some have it on, some have it off
      shell: echo off > /sys/devices/system/cpu/smt/control
      when: "smt.stdout == 'on'" # deals with notsupported case in packer VM
    - name: rerun facts
      setup:
    
    # - name: Check processor count for compute nodes
    #   set_fact:
    #     pre_total_cores: "{{ dict(groups['compute'] | zip(groups['compute'] | map('extract', hostvars) | map(attribute='ansible_processor_vcpus') )) }}"
    #   run_once: true
    
    # - assert:
    #     that: pre_total_cores | unique | length == 1
    #     fail_msg: "Different numbers of cores in 'compute' nodes:\n{{ pre_total_cores | to_nice_yaml }}"
    #     success_msg: "Core counts ok"
    #   run_once: true
