- hosts: all
  become: true
  tags: etc_hosts
  tasks:
    - name: Create /etc/hosts for all nodes as DNS doesn't work
      blockinfile:
        path: /etc/hosts
        create: yes
        state: present
        block: |
          {% for hostname in groups['all'] %}
          {{ hostvars[hostname]['ansible_host'] }} {{ hostname }}
          {% endfor %}
