- hosts: all
  become: true
  tags: squid
  tasks:
    - name: Configure yum proxy
      lineinfile:
        path:  /etc/yum.conf
        regexp: '^proxy=http://10\.60\.102\.179:3128'
        line: 'proxy=http://10.60.102.179:3128'

- hosts: all
  become: true
  tags: etc_hosts
  tasks:
    - name: Create /etc/hosts for all nodes
      blockinfile:
        path: /etc/hosts
        create: yes
        state: present
        block: "{{ host_ips | zip(host_names) | map('join', ' ') | join('\n') }}"
      vars:
        host_ips: "{{ groups['all'] | map('extract', hostvars, 'ansible_host') | list }}"
        host_names: "{{ groups['all'] | map('extract', hostvars, 'inventory_hostname') | list }}"
    
