- hosts: localhost
  become: false
  tags: build
  tasks:
    - name: Ensure secrets generated
      include_role:
        name: passwords
    
    - name: Build packer images
      shell:
        cmd: |
          cd packer
          PACKER_LOG=1 packer build -on-error=ask -var-file=$PKR_VAR_environment_root/builder.pkrvars.hcl openstack.pkr.hcl
        chdir: "{{ lookup('env', 'APPLIANCES_REPO_ROOT') }}"
      when: "'builder' not in group_names" # avoid recursion!
      register: packer_run
      async: 2700 # 45 minutes
      poll: 0

- hosts: all
  become: true
  tags: squid
  tasks:
    - name: Configure yum proxy
      lineinfile:
        path:  /etc/yum.conf
        regexp: '^proxy=http://10\.60\.102\.179:3128'
        line: 'proxy=http://10.60.102.179:3128'

- hosts: all
  become: true
  tags: etc_hosts
  tasks:
    - name: Create /etc/hosts for all nodes as DNS doesn't work
      blockinfile:
        path: /etc/hosts
        create: yes
        state: present
        block: "{{ host_ips | zip(host_names) | map('join', ' ') | join('\n') }}"
      vars:
        host_ips: "{{ groups['all'] | map('extract', hostvars, 'ansible_host') | list }}"
        host_names: "{{ groups['all'] | map('extract', hostvars, 'inventory_hostname') | list }}"
