- hosts: all
  become: true
  tags: squid
  tasks:
    - name: Configure yum proxy
      lineinfile:
        path:  /etc/yum.conf
        regexp: '^proxy=http://10\.60\.102\.179:3128'
        line: 'proxy=http://10.60.102.179:3128'

- hosts: all
  become: true
  tags: etc_hosts
  tasks:
    - name: Generate /etc/hosts file content
      # which interface is used as ansible_host is defined by terraform (see `access_network`) so this is deterministic for multi-rail hosts
      set_fact:
        etc_hosts_content: |
          {% for host in groups['cluster'] %}{{ hostvars[host]['ansible_host'] }} {{ host }}.novalocal {{ host }}
          {% endfor %}
      run_once: true
    - name: Create /etc/hosts for all nodes
      blockinfile:
        path: /etc/hosts
        create: yes
        state: present
        block: "{{ hostvars[ansible_play_hosts | first].etc_hosts_content }}"
