- hosts: all # NB: As this doesn't exclude `builder` /etc/hosts is baked into images, which should let `openstack server rebuild` work
  become: true
  tags: etc_hosts
  tasks:
    - name: Create /etc/hosts for all nodes as DNS doesn't work
      blockinfile:
        path: /etc/hosts
        create: yes
        state: present
        block: |
          {% for hostname in groups['all'] %}
          {{ hostvars[hostname]['ansible_host'] }} {{ hostname }}
          {% endfor %}

- hosts: control
  become: yes
  gather_facts: false
  tasks:
    - name: Write CI-generated inventory and secrets for debugging
      ansible.builtin.copy:
        dest: /etc/ci-config/
        src: "{{ item }}"
        directory_mode: 0400
        mode: 0400
        owner: root
        group: root
      #no_log: true
      no_log: false
      loop:
        - "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/inventory/hosts"
        - "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/inventory/group_vars/all/secrets.yml"
    - name: Write testuser password for debugging
      ansible.builtin.copy:
        dest: /etc/ci-config/testuser
        content: "{{ test_user_password }}"
        mode: 0400
        owner: root
        group: root
      no_log: true
