openhpc_rebuild_clouds: ~/.config/openstack/clouds.yaml # TODO: rename?

# TODO: should this get moved??
autoscale_suspend_exc_nodes: "{{ (groups.get('compute', []) + groups.get('login', [])) }}" # i.e. all non-CLOUD nodes, and prevent login-only slurmd nodes getting powered down
