autoscale_openhpc_suspend_exc_nodes: "{{ (groups.get('compute', []) + groups.get('login', [])) }}" # i.e. all nodes in inventory, i.e. not in State=CLOUD initially
autoscale_openhpc_config:
  # required parameters:
  SlurmctldParameters: enable_configless,idle_on_node_suspend,cloud_dns
  CommunicationParameters: NoAddrCache
  SuspendProgram: /opt/slurm-tools/bin/suspend
  ResumeProgram: /opt/slurm-tools/bin/resume
  # recommended:
  PrivateData: cloud # shows cloud node state
  # TODO: for testing only, not production:
  DebugFlags: PowerSave
  SlurmctldSyslogDebug: info
  SuspendTime: 120
  SuspendTimeout: 30
  ResumeTimeout: 300
  # FIXME: maybe need to set TreeWidth to >= number of nodes (default: 50)
  # power_save_*interval: options are defaults but should enable changes
openhpc_rebuild_clouds: ~/.config/openstack/clouds.yaml # TODO: fix name here?
