autoscale_clouds: ~/.config/openstack/clouds.yaml
# TODO: change below to be defined somewhere else, poss as part of slurm config for partition??
autoscale_image: ohpc-compute-210909-1316.qcow2
autoscale_network: stackhpc-ipv4-geneve
autoscale_flavor: general.v1.small
autoscale_keypair: centos-at-steveb-ansible

openhpc_suspend_exc_nodes: "{{ (groups['compute'] + groups.get('login', [])) }}" # i.e. all tf-defined nodes in the partition # TODO: fixme: hardcoded "compute"
autoscale_openhpc_extra_config:
  # required parameters:
  SlurmctldParameters: enable_configless,idle_on_node_suspend,cloud_dns
  CommunicationParameters: NoAddrCache
  SuspendProgram: /opt/slurm-tools/bin/suspend
  ResumeProgram: /opt/slurm-tools/bin/resume
  # recommended:
  PrivateData: cloud # shows cloud node state
  # TODO: for testing only, not production:
  DebugFlags: PowerSave
  SlurmctldSyslogDebug: info
  SuspendTime: 120
  SuspendTimeout: 30
  ResumeTimeout: 300
  # FIXME: maybe need to set TreeWidth to >= number of nodes (default: 50)
  # power_save_*interval: options are defaults but should enable changes
openhpc_rebuild_clouds: ~/.config/openstack/clouds.yaml