cloud_init_output_path: "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/cloud_init"

cloud_init_userdata_etchosts:
  module: write_files
  group: etc_hosts
  template: |-
    # etc_hosts group:
      - path: /etc/hosts
        encoding: text/plain
        permissions: "0644"
        owner: root:root
        content: |
            127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
            ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

            {% for hostname in groups['etc_hosts'] | sort -%}
            {{ hostvars[hostname]['ansible_host'] }} {{ hostname }}
            {% endfor -%}

cloud_init_nfsclients:
  module: mounts
  group: nfs
  template: |-
    # nfs_configurations:
    {% for nfs_cfg in nfs_configurations | default([]) %}{% if nfs_cfg.nfs_enable.clients | default(nfs_enable.clients) | default(false) | bool %}
      - ["{{ nfs_cfg.nfs_server }}:{{ nfs_cfg.nfs_export }}", "{{ nfs_cfg.nfs_client_mnt_point }}", "nfs", "defaults", "0", "0"]
    {% endif %}{% endfor %}

cloud_init_slurm_control_addr:
  module: write_files
  group: openhpc # gets templated into control host too but doesn't matter
  template: |-
    # openhpc - slurm control host for slurmd
      - path: /etc/sysconfig/slurmd
        encoding: text/plain
        permissions: "0644"
        owner: root:root
        content: SLURMD_OPTIONS='--conf-server {{ openhpc_slurm_control_host }}'

cloud_init_mungekey:
  module: write_files
  group: openhpc
  template: |-
    # openhpc_munge_key:
      - path: /etc/munge/munge.key
        encoding: base64
        permissions: "0400"
        owner: munge:munge
        content: {{ openhpc_munge_key | b64encode}}

cloud_init_os_creds:
  module: write_files
  group: rebuild
  template: |-
    # openhpc_rebuild_clouds:
      - path: /etc/openstack/clouds.yaml
        encoding: text/plain
        permissions: "0400"
        owner: root:root
        content: |
            {{ lookup('file', openhpc_rebuild_clouds) | indent(width=8, first=false) }}

cloud_init_basic_users:
  module: users
  group: basic_users
  template: |-
    # basic_users:
    # NB: https://cloudinit.readthedocs.io/en/latest/topics/modules.html#users-and-groups states using a str for uid is depreciated and to use an int.
    # however /usr/lib/python3.6/site-packages/cloudinit/distros/__init__.py shows it is ignored if NOT a str at v21.1-15.el8_6.3 at least
      - default
    {% for user in basic_users_users %}
      - name: {{ user.name }}
        passwd: {{ user.password }}
        uid: '{{ user.uid }}'
        no_create_home: true
    {% endfor %}

cloud_init_userdata_templates_default: # provides indirection so environments could copy parts of default without having to rewrite the entire thing
  - "{{ cloud_init_userdata_etchosts }}"
  - "{{ cloud_init_nfsclients }}"
  - "{{ cloud_init_slurm_control_addr }}"
  - "{{ cloud_init_mungekey }}"
  - "{{ cloud_init_os_creds }}"
  - "{{ cloud_init_basic_users }}"

cloud_init_userdata_templates_extra: []
cloud_init_userdata_templates: "{{ cloud_init_userdata_templates_default + cloud_init_userdata_templates_extra }}"
