---
# See: https://github.com/stackhpc/ansible-role-openhpc
# for variable definitions

openhpc_enable:
  control: "{{ inventory_hostname in groups['control'] }}"
  batch: "{{ inventory_hostname in groups['compute'] }}"
  database: "{{ inventory_hostname in groups['control'] }}"
  runtime: true
openhpc_slurm_service_enabled: true
openhpc_slurm_accounting_storage_type: 'accounting_storage/slurmdbd'
openhpc_slurmdbd_mysql_database: slurm_acct_db
openhpc_slurmdbd_mysql_password: "{{ vault_mysql_slurm_password }}"
openhpc_slurmdbd_mysql_username: slurm
openhpc_slurm_control_host: "{{ groups['control'] | first }}"
openhpc_slurm_partitions:
  - name: "compute"

# TODO: WIP PR to change/deprecate name here:
openhpc_packages_default:
  - slurm-libpmi-ohpc # to allow intel mpi to work properly
  - ohpc-gnu9-openmpi4-perf-tools # for hpctests
  - openblas-gnu9-ohpc # for hpctests (HPL)
openhpc_packages_extra: []
openhpc_packages: "{{ openhpc_packages_default + openhpc_packages_extra }}"

openhpc_munge_key: "{{ vault_openhpc_mungekey | b64decode }}"
openhpc_slurm_configless: true
openhpc_login_only_nodes: login

openhpc_config_default: "{{ rebuild_openhpc_extra_config | combine(autoscale_openhpc_extra_config) }}" # TODO: handle case where groups aren't defined!
openhpc_config_extra: {}
# TODO: WIP PR for openhpc_extra_config -> openhpc_config
openhpc_config: "{{ openhpc_config_default | combine(openhpc_config_extra) }}"

openhpc_suspend_exc_nodes_default:  "{{ autoscale_openhpc_suspend_exc_nodes }}" # TODO: handle cases where groups aren't defined
openhpc_env_suspend_exc_nodes_extra: []
openhpc_suspend_exc_nodes: "{{ openhpc_suspend_exc_nodes_default + openhpc_env_suspend_exc_nodes_extra }}"
