# Must be within K3s' reserved port range (default 30000-32767)
prometheus_port: 30000

prometheus_image_tag: "v2.27.0"

prometheus_db_dir: "{{ appliances_state_dir }}/prometheus"
prometheus_storage_retention: "30d"
prometheus_volume_size: 40Gi
prometheus_storage_retention_size: "40GB"
prometheus_scrape_configs_default:
- job_name: "slurm_exporter"
  scrape_interval: 30s
  scrape_timeout: 30s
  static_configs:
    - targets:
      - "{{ control_ip }}:{{ slurm_exporter_port }}"
  relabel_configs:
  # strip off port
  - source_labels: ['__address__']
    separator:     ':'
    regex:         '(.*):.*'
    target_label:  'instance'
    replacement:   '${1}'

prometheus_scrape_configs: "{{ prometheus_scrape_configs_default + (openondemand_scrape_configs if groups['openondemand'] | count > 0 else []) }}"
prometheus_extra_alert_rules:
  - alert: SlurmNodeDown
    annotations:
      message: '{% raw %}{{ $value }} Slurm nodes are in down status.{% endraw %}'
      summary: 'At least one Slurm node is down.'
    expr: "slurm_nodes_down > 0\n"
    labels:
      severity: critical
