_systemd_requiresmount_statedir: |
  [Unit]
  RequiresMountsFor={{ appliances_state_dir }}

# Modify systemd units to account for appliances_state_dir
_systemd_dropins_statedir:
  # mysql not included as role handles state dir correctly
  - unit: opendistro
    group: opendistro
    content: "{{ _systemd_requiresmount_statedir }}"
  - unit: grafana-server
    group: grafana
    content: "{{ _systemd_requiresmount_statedir }}"
  - unit: slurmdbd
    group: openhpc
    content: "{{ _systemd_requiresmount_statedir }}"
  - unit: slurmctld
    group: openhpc
    content: "{{ _systemd_requiresmount_statedir }}"
  - unit: prometheus
    group: prometheus
    content: "{{ _systemd_requiresmount_statedir }}"

# Modify systemd units which will have config provided by cloud_init:
_systemd_dropins_cloud_init_cfg:
  - unit: munge
    group: openhpc
    content: |
      [Unit]
      After=cloud-final.service
  # -unit: slurmd,slurmctld: already depend on munge so indirectly on cloud_init
  - unit: httpd
    group: openondemand
    content: |
      [Unit]
      After=cloud-final.service
      
      [Service]
      EnvironmentFile=/etc/sysconfig/openondemand

systemd_dropins_default: "{{ _systemd_dropins_cloud_init_cfg + (_systemd_dropins_statedir if appliances_state_dir is defined else  []) }}"
systemd_dropins_extra: [] # allows easy expansion in environments
systemd_dropins: "{{ systemd_dropins_default + systemd_dropins_extra }}"