all:
  vars:
    # required:
    cluster_name: templatetf # FIXME: needs defining for each arcus cluster!
    image_name: openhpc-221118-1422.qcow2 # https://github.com/stackhpc/slurm_image_builder/pull/12
    flavor: vm.alaska.cpu.general.small
    key_pair: slurm-app-ci
    network_name: WCDC-iLab-60
    subnet_name: WCDC-iLab-60
    
    # overrides:
    vnic_type: direct
    block_device_prefix: sd
    home_volume_size: 10
    state_volume_size: 10

    openhpc_slurm_partitions:
      - name: small
      - name: extra

# compute must contain child groups matching openhpc_slurm_partitions
compute:
  children:
    small:
      hosts:
        compute-[0:1]:
    extra:
      hosts:
        compute-[2:3]:
