all:
  vars:
    # REQUIRED variables:
    cluster_key_pair: slurm-app-ci
    cluster_name: "{{ lookup('env', 'CI_CLUSTER_NAME') }}"
    node_image_name: openhpc-221118-1422.qcow2 # https://github.com/stackhpc/slurm_image_builder/pull/12 TODO: FIXME
    node_flavor: vm.alaska.cpu.general.small
    node_network_name: WCDC-iLab-60
    node_subnet_name: WCDC-iLab-60
    
    # OPTIONAL variables:
    openhpc_slurm_partitions:
      - name: extra
      - name: small

    # overrides:
    home_volume_size: 10 # only need tiny volumes for CI/test
    state_volume_size: 10
    state_volume_device_path: /dev/sdb # have virtio-scsi enabled on image
    home_volume_device_path: /dev/sdc
    node_vnic_type: direct # on rdma-capable network
    

# compute must contain child groups matching openhpc_slurm_partitions
compute:
  children:
    small:
      hosts:
        compute-[0:1]:
    extra:
      hosts:
        compute-[2:3]:
