all:
  vars:
    # REQUIRED variables:
    cluster_key_pair: slurm-app-ci
    cluster_name: "{{ lookup('env', 'CI_CLUSTER_NAME') }}"
    cluster_network_name: WCDC-iLab-60
    node_interfaces:
      - network_name: "{{ cluster_network_name }}"
        security_groups: "{{ node_default_security_groups }}"
        binding:
          vnic_type: direct
    # cluster_subnet_name: WCDC-iLab-60
    node_image_name: openhpc-230106-1107.qcow2 # https://github.com/stackhpc/slurm_image_builder/pull/13
    node_flavor: vm.alaska.cpu.general.small
    
    # OPTIONAL variables:
    openhpc_slurm_partitions:
      - name: extra
      - name: small

    # overrides:
    home_volume_size: 10 # only need tiny volumes for CI/test
    state_volume_size: 10
    state_volume_device_path: /dev/sdb # have virtio-scsi enabled on image
    home_volume_device_path: /dev/sdc

control:
  hosts:
    control:
  vars:

login:
  hosts:
    login:
  vars:

# compute must contain child groups matching openhpc_slurm_partitions
compute:
  children:
    small:
      hosts:
        compute-[0:1]:
    extra:
      hosts:
        compute-[2:3]:
