
- hosts: login[0]
  become: yes
  gather_facts: no
  tasks:
    - import_role:
      name: users
      tasks_from: setup.yml
      vars:
        users: "{{ alaska_users }}"
        homedir: "{{ alaska_homedir }}"

- hosts: compute
  become: yes
  gather_facts: no
  tasks:
    - import_role:
      name: users
      tasks_from: propagate.yml
      users: "{{ alaska_users }}"
      homedir: "{{ alaska_homedir }}"
