- hosts: control
  become: true
  tasks:
    - name: Prevent ansible_user's processes being killed on compute nodes at job completion
      replace:
        path: /etc/slurm/slurm.epilog.clean
        regexp: 'if \[ \$SLURM_UID -lt 100 \] ; then'
        replace: "if [[ $SLURM_UID -lt 100 || $SLURM_JOB_USER -eq {{ ansible_user }} ]] ; then"
    - name: Make a /home/test directory for centos
      file:
        path: /home/test
        state: directory
        owner: centos
        group: centos
    - name: Install ewatch
      git:
        repo: https://github.com/sjpb/ewatch.git
        dest: /home/test/ewatch
        force: yes
