---
# vtest post.yml

- name: Include local deployment tasks when...
  hosts: all
  become: true
  tags:
    - local_deploy
  tasks:
    - include_tasks: site_post.yml
   #when: STACKHPC_DO_CI is not defined
   # or something like: '{{ lookup('env', 'STACKHPC_CI') }}' is not defined  or HOSTNAME is XXXX.stackhpc.org

- name: install X stuff from powertools to login hosts
  hosts: login
  become: true
  vars:
    packages:
      - xorg-x11-server-Xorg
      - xorg-x11-xauth
      - xorg-x11-apps
  tags:
    - post_powertools
    - post_x11
  tasks:
    - yum:
        #enablerepo: powertools
        state: present
        name: "{{ packages }}"
