# safe to use during build

- name: Increase maximum number of virtual memory maps
  # see https://opensearch.org/docs/2.0/opensearch/install/important-settings/
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present
    reload: yes

- name: Pull container image
  containers.podman.podman_image:
    name: docker.io/opensearchproject/opensearch
    tag: "{{ opensearch_version }}"
  become_user: "{{ opensearch_podman_user }}"
