# TODO: make this so only remove ones which AREN'T required
- name: Remove old build templates
  ansible.builtin.shell: rm -f {{ builder_dir }}*build.pkr.hcl

- name: Create build templates
  ansible.builtin.template:
    src: openstack.pkr.hcl.j2
    dest: "{{ builder_dir }}/{{ build_name }}.pkr.hcl"
  loop: "{{ builder_images }}"
  vars:
    build_name: "{{ item }}"
    
# - name: Run build
#   ansible.builtin.shell:
#     cmd: PACKER_LOG=1 /usr/bin/packer build -on-error=ask -var-file=$PKR_VAR_environment_root/builder.pkrvars.hcl . | tee build.out
#     chdir: "{{ lookup('env', 'APPLIANCES_REPO_ROOT') }}/packer"
#   # async: "{{ 60 * 60 }}" # wait for up to an hour
#   # poll: 5
#   register: build_run
