- name: nrel-proto fixes - workaround no internal DNS
  hosts:
    - cluster
    - localhost
  become: true
  tags: etc_hosts
  tasks:
    - name: Internal DNS workaround - generate /etc/hosts file content
      set_fact: # TODO: define which network to use below:
        etc_hosts_content: |
          {% for host in groups['cluster'] %}{{ hostvars[host]['ansible_default_ipv4']['address'] }} {{ host }}.novalocal {{ host }}
          {% endfor %}
      run_once: true
    - name: Internal DNS workaround  - create entries in /etc/hosts for all nodes
      blockinfile:
        path: /etc/hosts
        create: yes
        state: present
        block: "{{ hostvars[ansible_play_hosts[0]].etc_hosts_content }}"

- name: nrel-proto fixes - compute nodes
  hosts: compute
  become: true
  tasks:
    - name: Create scratch directory - should be on local SSD on real cluster
      file:
        path: /tmp/scratch
        state: directory

