nfs_rdma: true

nfs_server: "{{ slurmctl_rdma_port_ip }}"

nfs_enable:
        server:  "{{ inventory_hostname in groups['control'] }}"
        # Don't mount share on server where it is exported from...
        # Could do something like nfs_clients: '"nfs_servers" not in group_names' instead.
        # See also constructed inventory: https://docs.ansible.com/ansible/devel/collections/ansible/builtin/constructed_inventory.html
        clients: "{{ inventory_hostname in groups['cluster'] and inventory_hostname not in groups['control'] }}"
nfs_export_options: rw,insecure,no_root_squash

nfs_configurations:
  - comment: Export /home from Slurm control node
    nfs_export: "/home"
    nfs_client_mnt_point: "/home"
  - comment: Export /scratch from Slurm control node (NVME drives)
    nfs_export: "/scratch"
    nfs_client_mnt_point: "/scratch"
