# Yaml-format ansible inventory with default hostvars. It should be overriden/extended by an environment's own cluster.yml file.
# NB: This is the lowest-possible priority - it will be overridden by inventory files in other inventories, 'all' group_vars, etc.
# Host and group vars defined here are available even when no hosts have been provisioned (e.g. during provisioning or image build).

all:
  vars:
    # REQUIRED variables - to be defined in an environment:
    cluster_key_pair: "{{ undef(hint='cluster_key_pair must be defined') }}"
    cluster_name: "{{ undef(hint='cluster_name must be defined') }}"
    cluster_network_name: "{{ undef(hint='cluster_network_name must be defined') }}"
    cluster_subnet_name: "{{ undef(hint='cluster_subnet_name must be defined') }}"
    node_image_name: "{{ undef(hint='node_image_name must be defined') }}"
    node_flavor: "{{ undef(hint='node_flavor must be defined') }}"

    # OPTIONAL variables:
    cluster_tld: invalid # top-level domain for cluster (FQDN is nodename.cluster_name.cluster_tld)
    node_fqdn: "{{ inventory_hostname }}.{{ cluster_name }}.{{ cluster_tld }}"
    node_tf_ignore_changes: [] # terraform attributes to ignore for node changes
    node_security_groups: ["default"]
    node_user_data: ''
    
    # openstack volume options - note hostvars too:
    state_volume_size: 150 # GB
    home_volume_size: 100 # GB
    state_volume_device_path: /dev/vdb
    home_volume_device_path: /dev/vdc
    node_volumes: []
    
    # terraform openstack_networking_port_v2:binding
    node_vnic_profile: {}
    node_vnic_type: normal

    # this default works when there are no child groups in the 'compute' group
    # and no partition customisation is required
    openhpc_slurm_partitions:
      - name: "compute"

control:
  hosts:
    control:
  vars:
    appliances_state_dir: /var/lib/state
    node_volumes:
      - label: state
        description: State for control node
        size: "{{ state_volume_size }}"
        mount_point: "{{ appliances_state_dir }}"
      - label: home
        description: Home for cluster
        size: "{{ home_volume_size }}"
        mount_point: /exports/home
        mount_options: 'x-systemd.required-by=nfs-server.service,x-systemd.before=nfs-server.service'
    node_user_data: |
      #cloud-config
      fs_setup:
        - label: state
          filesystem: ext4
          device: {{ state_volume_device_path }}
          partition: auto
        - label: home
          filesystem: ext4
          device: {{ home_volume_device_path }}
          partition: auto
      mounts:
        - [LABEL=state, {{ appliances_state_dir }}]
        - [LABEL=home, /exports/home, auto, "x-systemd.required-by=nfs-server.service,x-systemd.before=nfs-server.service"]

login:
  hosts:
    login:
  vars:
    node_security_groups:
      - default
      - SSH
      - HTTPS
