- name: Create mysql pod
  kubernetes.core.k8s:
    template: "{{ item }}"
    namespace: default
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    # wait: true # TODO: needs supporting specifically for pvc
  loop:
    - mysql-pvc.yaml.j2
    - mysql-deployment.yaml.j2
