- name: Install pip
  dnf:
    name: python3-pip

- name: Install python mysql client
  pip:
    name:
      - pymysql
      - cryptography
    state: present

- name: Pull container image
  containers.podman.podman_image:
    name: docker.io/library/mysql
    tag: "{{ mysql_tag }}"
  become_user: "{{ mysql_podman_user }}"
