- name: Install pip
  dnf:
    name: python3-pip

- name: Install python packages
  # TODO: FIXME: doing this in the system python doesn't seem right
  pip:
    name:
      - kubernetes # TODO: move this to k8s module?
    state: present
