- name: Install python mysql client
  pip:
    name: pymysql
    state: present

- name: Pull container image
  containers.podman.podman_image:
    name: "mysql"
    tag: "{{ mysql_tag }}"
  become_user: "{{ mysql_podman_user }}"
