---
- name: Install EPEL repo
  package:
    name: epel-release

- name: Install fail2ban packages
  package:
    name:
      - fail2ban-server
      - fail2ban-firewalld
    state: present

- name: Put cluster subnet into firewalld's trusted zone
  ansible.posix.firewalld:
    permanent: yes
    source: "{{ fail2ban_trusted_subnet }}"
    zone: trusted
    state: enabled
  notify: Restart filewalld

- name: Create config
  template:
    dest: /etc/fail2ban/jail.local
    src: jail.local.j2
  notify: Restart fail2ban

- name: flush handlers
  meta: flush_handlers

- name: Ensure filewalld running even if no config change
  service:
    name: firewalld
    state: started
    enabled: true

- name: Ensure fail2ban running even if no config change
  service:
    name: fail2ban
    state: started
    enabled: true
