---
# tasks file for yum_config

- name: copy rocky8 yum repo configs
  copy:
    dest: "/etc/yum.repos.d/{{ item }}"
    src:  "./rocky8/{{ item }}"
    backup: False # not required. Create a backup file including the timestamp information so you can get the original file back if you somehow clobbered it incorrectly.
    mode: 0644
    owner:  # not required. Name of the user that should own the file/directory, as would be fed to I(chown).
    group:  # not required. Name of the group that should own the file/directory, as would be fed to I(chown).
  loop:
    - "Rocky-AppStream.repo"
    - "Rocky-BaseOS.repo"
    - "Rocky-Debuginfo.repo"
    - "Rocky-Devel.repo"
    - "Rocky-Extras.repo"
    - "Rocky-HighAvailability.repo"
    - "Rocky-Media.repo"
    - "Rocky-NFV.repo"
    - "Rocky-Plus.repo"
    - "Rocky-PowerTools.repo"
    - "Rocky-ResilientStorage.repo"
    - "Rocky-RT.repo"
    - "Rocky-Sources.repo"
    - cuda-rhel8.repo
    - epel-modular.repo
    - epel.repo

  when: (ansible_distribution == "Rocky") and (ansible_distribution_major_version == "8")
