cloud_init_output_path: "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/cloud_init"
cloud_init_userdata_template: |
  #cloud-config
  disable_ec2_metadata: true

  mounts:
  # nfs_configurations:
  {% for nfs_cfg in nfs_configurations | default([]) %}{% if nfs_cfg.nfs_enable.clients | default(nfs_enable.clients) | default(false) | bool %}
    - ["{{ nfs_cfg.nfs_server }}:{{ nfs_cfg.nfs_export }}", "{{ nfs_cfg.nfs_client_mnt_point }}", "nfs", "defaults", "0", "0"]
  {% endif %}{% endfor %}

  write_files:
  {% if 'etc_hosts' in group_names %}
    - path: /etc/hosts
      encoding: text/plain
      permissions: "0644"
      owner: root:root
      content: |
          127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
          ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

          # BEGIN ANSIBLE MANAGED BLOCK
          {{ etc_hosts_template | indent(width=8, first=false) | trim }}
          # END ANSIBLE MANAGED BLOCK
  {% endif %}

  {% if 'openhpc' in group_names %}{# gets templated into control host too but doesn't matter #}
    # openhpc_slurm_control_host:
    - path: /etc/sysconfig/slurmd
      encoding: text/plain
      permissions: "0644"
      owner: root:root
      content: SLURMD_OPTIONS='--conf-server {{ openhpc_slurm_control_host }}'
  {% endif %}

  {% if 'openhpc' in group_names %}
    # openhpc_munge_key:
    - path: /etc/munge/munge.key
      encoding: base64
      permissions: "0400"
      owner: munge:munge
      content: {{ openhpc_munge_key | b64encode}}
  {% endif %}

  {% if 'rebuild' in group_names %}
    # openhpc_rebuild_clouds:
    - path: /etc/openstack/clouds.yaml
      encoding: text/plain
      permissions: "0400"
      owner: root:root
      content: |
          {{ lookup('file', openhpc_rebuild_clouds) | indent(width=8, first=false) }}
  {% endif %}

  {% if 'basic_users' in group_names %}
  # basic_users:
  # NB: https://cloudinit.readthedocs.io/en/latest/topics/modules.html#users-and-groups states using a str for uid is depreciated and to use an int.
  # however /usr/lib/python3.6/site-packages/cloudinit/distros/__init__.py shows it is ignored if NOT a str at v21.1-15.el8_6.3 at least
  users:
    - default
  {% for user in basic_users_users %}
    - name: {{ user.name }}
      passwd: {{ user.password }}
      uid: '{{ user.uid }}'
      no_create_home: true
  {% endfor %}
  {% endif %}
