---

- name: Make directory
  file:
    path: "{{ hpctests_rootdir }}/hpl"
    state: directory

- name: Download HPL sources
  unarchive:
    src: "http://www.netlib.org/benchmark/hpl/hpl-{{ hpctests_hpl_version }}.tar.gz"
    remote_src: yes
    dest: "{{ hpctests_rootdir }}/hpl"
    keep_newer: yes

- name: Copy BLAS make file
  command:
    cmd: cp setup/Make.Linux_PII_CBLAS Make.linux64
    chdir: "{{ hpctests_hpl_srcdir }}"
    creates: "{{ hpctests_hpl_srcdir }}/Make.linux64"

- name: Modify make file
  replace:
    path: "{{ hpctests_hpl_srcdir }}/Make.linux64"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - regexp: '^TOPdir.*$'
      replace: "TOPdir       = {{ hpctests_hpl_srcdir }}"
    - regexp: '^ARCH\s+=.*$'
      replace: "ARCH         = linux64"
    - regexp: '^MPdir.*$'
      replace: "MPdir        = $(MPI_DIR)"
    - regexp: '^MPinc.*$'
      replace: "MPinc        = -I$(MPI_DIR)/include"
    - regexp: '^MPlib.*$'
      replace: "MPlib        = $(MPI_DIR)/lib/libmpi.so"
    - regexp: '^LAdir.*$'
      replace: "LAdir        = $(OPENBLAS_DIR)"
    - regexp: '^LAinc.*$'
      replace: "LAinc        ="  # not sure if this one is needed?
    - regexp: '^LAlib.*$'
      replace: "LAlib        = $(OPENBLAS_LIB)/libopenblas.so"
    - regexp: '^CC\s+=.*$'
      replace: "CC           = mpicc"
    - regexp: '^LINKER\s+=.*$'
      replace: "LINKER       = mpicc"

- name: Build HPL executable
  shell:
    cmd: |
      set -e
      . /etc/profile
      module load {{ hpctests_hpl_modules | join(' ' ) }}
      make arch=linux64 clean_arch_all
      make arch=linux64
    chdir: "{{ hpctests_hpl_srcdir }}"
    creates: "bin/linux64/xhpl"
