- name: workaround no internal DNS
  hosts:
    - cluster
  become: true
  tags: etc_hosts
  tasks:
    - name: Internal DNS workaround - generate /etc/hosts file content
      # which interface is used as ansible_host is defined by terraform (see `access_network`) so this is deterministic for multi-rail hosts
      set_fact:
        etc_hosts_content: |
          {% for host in groups['cluster'] %}{{ hostvars[host]['ansible_host'] }} {{ host }}.novalocal {{ host }}
          {% endfor %}
      run_once: true
    - name: Internal DNS workaround  - create entries in /etc/hosts for all nodes
      blockinfile:
        path: /etc/hosts
        create: yes
        state: present
        block: "{{ hostvars[ansible_play_hosts[0]].etc_hosts_content }}"
  
- name: Install Mellanox OFED
  hosts: mofed
  become: true
  tags: mofed
  tasks:
    - import_role: # NB: this will change the kernel if necessary!
        name: stackhpc.ofed
    - name: Reboot if required from kernel change
      reboot:
        post_reboot_delay: 30
      when: grub_update_result.changed
    - name: update facts
      setup:
      when: grub_update_result.changed
