openhpc_packages_extra:
  - slurm-libpmi-ohpc
  - bzip2
  - curl
  - fio
  - libaio
  - libaio-devel
  - git
  - gzip
  - make
  - patch
  - python3
  - tar
  - unzip
  - wget
  - xz
  - zstd
  - tmux
  - vim
  - slurm-libpmi-ohpc
  - slurm-sview-ohpc
  - gnu9-compilers-ohpc
  - nhc-ohpc
  - lmod-ohpc
  - ohpc-autotools
  - ohpc-base
  - ohpc-base-compute
  - openblas-gnu9-ohpc
  - ohpc-gnu9-openmpi4-perf-tools
  - mpich-ofi-gnu9-ohpc
  - mpich-ucx-gnu9-ohpc
  - mvapich2-gnu9-ohpc
  - openmpi4-gnu9-ohpc
  - ucx-ohpc
  - hdf5-gnu9-ohpc
  - netcdf-gnu9-impi-ohpc
  - netcdf-gnu9-mpich-ohpc
  - netcdf-gnu9-mvapich2-ohpc
  - netcdf-gnu9-openmpi4-ohpc
  - phdf5-gnu9-impi-ohpc
  - phdf5-gnu9-mpich-ohpc
  - phdf5-gnu9-mvapich2-ohpc
  - phdf5-gnu9-openmpi4-ohpc
  - pnetcdf-gnu9-impi-ohpc
  - pnetcdf-gnu9-mpich-ohpc
  - pnetcdf-gnu9-mvapich2-ohpc
  - pnetcdf-gnu9-openmpi4-ohpc
  - charliecloud-ohpc
  - singularity-ohpc
  - boost-gnu9-impi-ohpc
  - boost-gnu9-mpich-ohpc
  - boost-gnu9-mvapich2-ohpc
  - boost-gnu9-openmpi4-ohpc
