---
- hosts: vermilion_nodes
  pre_tasks:
    - name: Verify Ansible meets version requirements.
      assert:
        that: "ansible_version.full is version_compare('2.5', '>=')"
        msg: >
          "You must update Ansible to at least version 2.5 to use this role."
  roles:
    - vermilion_ldap_client

  # vars:
   # see defaults/main.yml
