- name: Gather Lustre interface info
  shell:
    cmd: |
      ip r get {{ _lustre_mgs_ip }}
  changed_when: false
  register: _lustre_ip_r_mgs
  vars:
    _lustre_mgs_ip: "{{ lustre_mgs_nid | split('@') | first }}"

- name: Set facts for Lustre interface
  set_fact:
    _lustre_interface: "{{ _lustre_ip_r_mgs_info[4] }}"
    _lustre_ip: "{{ _lustre_ip_r_mgs_info[6] }}"
  vars:
    _lustre_ip_r_mgs_info: "{{ _lustre_ip_r_mgs.stdout_lines.0 | split }}"
    # first line e.g. "10.167.128.1 via 10.179.0.2 dev eth0 src 10.179.3.149 uid 1000"

- name: Write LNet configuration file
  template:
    src: lnet.conf.j2
    dest:  /etc/lnet.conf # exists from package install, expected by lnet service
    owner: root
    group: root
    mode: u=rw,go=r # from package install
  register: _lnet_conf

- name: Ensure lnet service state
  systemd:
    name: lnet
    state: "{{ 'restarted' if _lnet_conf.changed else 'started' }}"

- name: Ensure mount points exist
  ansible.builtin.file:
    path: "{{ lustre_mount_point }}"
    state: directory
  when: "lustre_mount_state != 'absent'"
# TODO: do we need to set owner/group/mode either pre- or post-mount?

# TODO: is this an ok way of doing it?
- name: Mount lustre filesystem
  ansible.posix.mount:
    fstype: lustre
    src: "{{ lustre_mgs_nid }}:/{{ lustre_fs_name }}"
    path: "{{ lustre_mount_point }}"
    state: "{{ lustre_mount_state }}"
    opts: "defaults,_netdev,noauto,x-systemd.automount,x-systemd.requires=lnet.service"
    # opts are systemd defaults from http://wiki.lustre.org/Mounting_a_Lustre_File_System_on_Client_Nodes
