---
- name: Setup volume for opendistro
  containers.podman.podman_volume:
    state: present
    name: opendistro
  become: true
  become_user: "{{ opendistro_podman_user }}"
  notify: Restart opendistro container

- name: Create systemd unit file
  template:
    dest: /etc/systemd/system/opendistro.service
    src: opendistro.service.j2
  become: true
  notify: Restart opendistro container

# - name: Get podman user ID
#   command: "id -u {{ opendistro_podman_user }}"
#   register: _podman_userid
#   changed_when: false

# [Service]
# User={{ opendistro_podman_user }}
# Group={{ opendistro_podman_user }}

# - name: Enable user lingering
#   command:
#     cmd: "loginctl enable-linger {{ opendistro_podman_user }}"
#     creates: "/var/lib/systemd/linger/{{ opendistro_podman_user }}"
#   become: yes
