---

- name: Modify openhpc_slurm_partitions
  set_fact:
    openhpc_slurm_partitions: "{{ openhpc_slurm_partitions | modify_autoscale_partitions }}"
- name: Merge autoscale configuration
  set_fact:
    openhpc_config: "{{ autoscale_openhpc_config | combine(openhpc_config, list_merge='append') }}"
