---

- name: Get cloud_node specs
  shell:
    cmd: "openstack flavor show --format json {{ item.cloud_instances.flavor }}"
  delegate_to: localhost
  run_once: true
  loop: "{{ openhpc_slurm_partitions }}"
  when: "'cloud_instances' in item"
  register: _os_flavors
  become: no
- name: Manipulate flavor information
  set_fact:
    flavor_info: "{{ _os_flavors.results | map(attribute='stdout') | map('from_json') }}" # list of json info
- debug:
    var: flavor_info
- name: Modify openhpc_slurm_partitions
  set_fact:
    openhpc_slurm_partitions: "{{ openhpc_slurm_partitions | modify_autoscale_partitions(flavor_info, openhpc_ram_multiplier) }}"
- name: Merge autoscale configuration
  set_fact:
    openhpc_config: "{{ autoscale_openhpc_config | combine(openhpc_config, list_merge='append') }}"
