# Test manila mounts
# This runs twice in CI:
# - Before rebuild, a single node writes the file and all nodes check access
# - After rebuild, all nodes check acceess

- hosts: manila
  become: no
  gather_facts: no
  name: Test manila mount on /scratch
  vars:
    testfile_path: /scratch/testfile
    testfile_content: Manila share test file
  tasks:
    - name: Check whether hpctests has run (if not, pre-rebuild in CI)
      stat:
        path: "{{ hpctests_rootdir }}"
      register: _hpctests_dir
    - name: Write test file on {{ testfile_path }}
      copy:
        dest: "{{ testfile_path }}"
        content: "{{ testfile_content }}"
      when: not _hpctests_dir.stat.exists | default(false)
      run_once: true
    - name: Retrieve test file
      slurp:
        path: "{{ testfile_path }}"
      register: _slurp_testfile
    - name: Check file contents
      assert:
        that: "_slurp_testfile.content | b64decode == testfile_content"
        fail_msg: "{{ testfile_path }} not found"
        success_msg: testfile contents ok
