---
# NOTE: Slurm cluster assummed to be operational

- name: Ensure the cluster exists in the accounting database
  sacct_cluster:
    name: "{{ openhpc_cluster_name }}"
    state: present
  run_once: true
  when:
    - openhpc_slurm_accounting_storage_type == 'accounting_storage/slurmdbd'
  # We need to restart to create the database table
  notify:
    - Restart slurmdbd service
    - Restart slurmctld service
