- name: Get tmp directory filesystem type
  command: stat -f -c %T {{ podman_tmp_dir_root }}
  register: podman_tmp_fstype
  changed_when: false
    
- name: Check tmp directory is on tmpfs
  assert:
    that: podman_tmp_fstype.stdout == 'tmpfs'
    fail_msg: "{{ podman_tmp_fstype }} (variable podman_tmp_fstype) must be on tmpfs"

- name: Check host IP is not within podman network CIDR
  assert:
    that: ( podman_cidr | ansible.netcommon.network_in_network(ansible_default_ipv4.address)) == false
    fail_msg: "Default ipv4 address {{ ansible_default_ipv4.address }} for {{ inventory_hostname }} is in podman network range {{ podman_cidr }} - set `podman_cidr` to avoid host network address range"