- hosts: localhost
  gather_facts: no
  become: no
  tasks:
    - name: Template out cloud-init userdata
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/userdata/{{ item | basename | splitext | first }}" # e.g. # .../environments/$ENV/userdata/compute.userdata.yml
      loop: "{{ userdata_templates }}"
      vars:
        userdata_templates: "{{ lookup('fileglob', lookup('env', 'APPLIANCES_REPO_ROOT') + '/environments/common/templates/*.userdata.yml.j2', wantlist=True) }}"
