- hosts: localhost
  become: no
  gather_facts: no
  tasks:
    - name: Create group for templating with 1x host per template group
      ansible.builtin.add_host:
        name: "cloud_init_{{ item.key }}"
        groups:
          - "{{ item.key }}"
          - cloud_init_templating
        ansible_host: localhost
      loop: "{{ cloud_init_userdata_templates | dict2items }}"
      changed_when: false

- hosts: cloud_init_templating
  become: no
  gather_facts: no
  tasks:
    - name: Template out cloud-init userdata
      import_role:
        name: cloud_init
        tasks_from: template.yml
      delegate_to: localhost
