# This is a version of ansible/adhoc/tests which is safe to use on an in-production cluster.
# Relies on installed packages - see openhpc variables.

---

- hosts: login[0] # TODO: might want to make this selectable?
  become: false
  gather_facts: false
  vars:
    hpctests_rootdir: "/home/hpctests" # TODO: make configurable in appliance
  tasks:
    - import_role:
        name: hpctests
