# NB: this only works on centos 8 / ohpc v2 as we want UCX
# TODO: add support for groups/partitions
# TODO: add support for combined login/control nodes?
# Prequisites:
# - slurm-libpmi-ohpc package - installed by default by openhpc role

# Use tags like this to run specific tests:
#   ansible-playbook ansible/adhoc/test.yml --tags pingmatrix
#
# Only works for default partition. If this isn't the entire set of compute nodes you must also limit it
# to those nodes, e.g.:
#   ansible-playbook ansible/adhoc/test.yml --tags pingmatrix openhpc_tests_nodes=hpc-[0-3]

- hosts: openhpc_tests
  name: Run tests
  gather_facts: true
  tasks:
    - import_role:
        name: stackhpc.slurm_openstack_tools.test
      # TODO: FIXME: need to fix /opt mount so that it only overrides /opt/intel and /opt/ohpc
      # TODO: FIXME: need to fix /opt unmount so it works
