- hosts: control
  gather_facts: no
  name: Provide site-specific configuration/secrets
  tasks:
    - name: Create compute node cloud-init userdata
      # on localhost allows use from TF and `openstack server rebuild`
      template:
        src: userdata/compute.j2
        dest: "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/userdata/compute.txt"
      # no_log: true
      delegate_to: localhost
    
    - name: Create directory for compute node cloud-init userdata
      file:
        path: /etc/slurm-appliance-userdata/ # TODO: move this to config volume once available # TODO: bikeshed name?
        state: directory
        mode: u=rw,go=
      become: yes

    - name: Push compute node cloud-init userdata to control node
      # on control allows for Slurm-based rebuild
      copy:
        src: "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/userdata/compute.txt"
        dest: /etc/slurm-appliance-userdata/compute.txt
        mode: u=rw,go=
      become: yes
