- hosts: basic_users:!builder
  become: yes
  tags:
    - basic_users
    - users
  gather_facts: yes
  tasks:
    - import_role:
        name: basic_users

- name: Setup EESSI
  hosts: eessi
  tags: eessi
  become: true
  gather_facts: false
  tasks:
    - name: Install and configure EESSI
      include_role:
        name: eessi
        tasks_from: "{{ appliances_task_mode }}.yml"

- name: Setup CUDA
  hosts: cuda
  become: yes
  gather_facts: no
  tags: cuda
  tasks:
    - import_role:
        name: cuda
      when: "{{ appliances_task_mode != 'configure' }}" # everything is install-time
