---

- name: Setup block devices
  hosts: block_devices
  become: yes
  tags: block_devices
  tasks:
    - include_role:
        name: block_devices

- name: Setup NFS
  hosts: nfs
  become: true
  tags:
    - nfs
  tasks:
    - include_role:
        name: stackhpc.nfs

- name: Setup Manila share mounts
  hosts: manila
  become: true
  tags: manila
  tasks:
    - include_role:
        name: stackhpc.os-manila-mount
        tasks_from: "{{ item }}.yml"
      loop: "{{ manila_task_modes[appliances_task_mode] }}"
      vars:
        manila_task_modes:
          main:
            - main
          runtime: # TODO: add a runtime.yml to this role
            - lookup
            - mount
          #install:
            # - install
