---

- name: Setup block devices
  hosts: block_devices
  become: yes
  tags: block_devices
  gather_facts: false
  tasks:
    - include_role:
        name: block_devices

- name: Setup NFS
  hosts: nfs
  become: true
  gather_facts: false
  tags:
    - nfs
  tasks:
    - include_role:
        name: stackhpc.nfs
