---

- name: Setup NFS
  hosts: nfs
  become: true
  tags:
    - nfs
  tasks:
    - include_role:
        name: stackhpc.nfs

- name: Mount Openstack Manila share
  hosts: os_manila
  tasks:
    - name: Mount Manila share
      include_role: os_manila_ceph
