---

- name: Setup NFS
  hosts: nfs
  become: true
  tags:
    - nfs
  tasks:
    - include_role:
        name: stackhpc.nfs

# Access a pre-existing filesystem with a pre-existing key
- name: Gather facts about OpenStack Manila share
  hosts: openstack
  tasks:
    - include_role: stackhpc.os-manila-mount
      vars:
        os_manila_mount_action: lookup
      # os_manila_mount_share_name: "{{ cluster_fileshare }}"
      # os_manila_mount_share_user: "{{ cluster_ceph_client }}"
      # os_manila_mount_auth_type: "{{ openstack_auth_type }}"
      # os_manila_mount_auth: "{{ openstack_auth }}"
    - debug:
        var: os_manila_mount_host
    - debug:
        var: os_manila_mount_export
    - debug:
        var: os_manila_mount_access_key

- name: Mount Openstack Manila share
  hosts: os_manila
  tasks:
    - name: Ensure the cluster home dir mount point exists
      file:
        path: "{{ cluster_homedir }}"
        state: directory
        recurse: yes
        owner: root
        group: root
        mode: 0755
      become: yes
    - name: Ensure the CentOS Ceph package archive is present
      package:
        name: "centos-release-ceph-octopus"
        state: present
      become: yes
    - name: Ensure the Ceph client packages are present
      package:
        name: "ceph-common"
        state: present
      become: yes
    - name: Mount Manila share
      include_role: stackhpc.os-manila-mount
      vars:
        os_manila_mount_action: "mount"
      
      # os_manila_mount_host: "{{ hostvars['localhost']['os_manila_mount_host'] }}"
      # os_manila_mount_access_key: "{{ hostvars['localhost']['os_manila_mount_access_key'] }}"
      # os_manila_mount_export: "{{ hostvars['localhost']['os_manila_mount_export'] }}"
      # os_manila_mount_share_name: "{{ cluster_fileshare }}"
      # os_manila_mount_share_user: "{{ cluster_ceph_client }}"
      # os_manila_mount_share_protocol: "CEPHFS"
      # os_manila_mount_path: "{{ cluster_homedir }}"
      # os_manila_mount_user: "root"
      # os_manila_mount_group: "root"
      # os_manila_mount_fuse: no
