# ---
# # NOTE: Requires slurmdbd

- name: Setup OpenSearch
  hosts: opensearch
  tags: opensearch
  tasks:
    - import_role:
        name: opensearch
        tasks_from: install.yml
      become: true
    - import_role:
        name: opensearch
        tasks_from: runtime.yml
      become: true

- name: Setup slurm stats
  hosts: slurm_stats
  tags: slurm_stats
  collections:
    - stackhpc.slurm_openstack_tools
  tasks:
    - include_role:
        name: slurm-stats
        apply:
          # Collection currently requires root for all tasks.
          become: true

- name: Deploy filebeat
  hosts: filebeat
  tags: filebeat
  tasks:
    - import_role:
        name: filebeat

- name: Install monitoring helm chart
  hosts: prometheus
  become: true
  tags: prometheus
  tasks:
    - ansible.builtin.import_role:
        name: kube_prometheus_stack

- name: Deploy OpenOndemand exporter
  hosts: openondemand
  become: true
  tags:
    - openondemand
    - openondemand_server
  tasks:
    - import_role:
        name: openondemand
        tasks_from: exporter.yml

- name: Deploy Slurm exporter
  hosts: control
  become: true
  tags: slurm_exporter
  tasks:
    - import_role:
        name: slurm_exporter
