# Output pure-json data from ansible with no task/play decorations,
# in the single-level format required by terraform's data.external resource
# Must be run with environment variable `ANSIBLE_STDOUT_CALLBACK=community.general.diy` set.

- hosts: localhost
  gather_facts: no
  become: no
  vars:
    ansible_callback_diy_playbook_on_play_start_msg: '' # suppress headers/footers
    ansible_callback_diy_playbook_on_task_start_msg: ''
    ansible_callback_diy_playbook_on_stats_msg: ''
    ansible_callback_diy_runner_on_ok_msg: "{{ ansible_callback_diy.result.output.msg }}" # don't print task status or hostname
  tasks:
    - debug:
        msg: "{{ secrets | to_json }}"
      vars:
        _missing_clouds_yaml_error: "{{ 'strict' if groups['rebuild'] else 'ignore' }}"
        secrets:
          openhpc_munge_key_b64: "{{ openhpc_munge_key | b64encode }}"
          clouds_yaml: "{{ lookup('file', openhpc_rebuild_clouds, errors=_missing_clouds_yaml_error) }}"
