- hosts: openondemand
  tags:
    - openondemand
    - openondemand_server
  become: yes
  gather_facts: yes # TODO
  tasks:
    - import_role:
        name: openondemand
        tasks_from: main.yml
    # this one is quite hard to sort for appliances_task_mode

- hosts: openondemand_desktop
  tags:
    - openondemand
    - openondemand_desktop
  become: yes
  gather_facts: yes
  tasks:
    - import_role:
        name: openondemand
        tasks_from: vnc_compute.yml
      when: "{{ appliances_task_mode != 'configure' }}" # is all install-time

- hosts: openondemand_jupyter
  tags:
    - openondemand
    - openondemand_jupyter
  become: yes
  gather_facts: yes
  tasks:
    - import_role:
        name: openondemand
        tasks_from: jupyter_compute.yml
      when: "{{ appliances_task_mode != 'configure' }}" # is all install-time
