- hosts: openondemand
  tags:
    - openondemand
    - openondemand_server
  become: yes
  gather_facts: false # TODO: check?
  tasks:
    - import_role:
        name: openondemand
        tasks_from: main.yml

- hosts: openondemand_desktop
  tags:
    - openondemand
    - openondemand_desktop
  become: yes
  gather_facts: false
  tasks:
    - import_role:
        name: openondemand
        tasks_from: vnc_compute.yml

- hosts: openondemand_jupyter
  tags:
    - openondemand
    - openondemand_jupyter
  become: yes
  gather_facts: false
  tasks:
    - import_role:
        name: openondemand
        tasks_from: jupyter_compute.yml
