---

- name: Setup DB
  hosts: mysql
  become: true
  tags:
    - mysql
  tasks:
    - include_role:
        name:  geerlingguy.mysql

- name: Enable Slurm/OpenStack integrations
  hosts:
    - rebuild
    - autoscale
  become: true
  tags:
    - rebuild
    - autoscale
    - openhpc
  tasks:
    - name: Install slurm packages to create slurm user
      import_role:
        name: stackhpc.openhpc
        tasks_from: install.yml
    - name: Create /etc/openstack
      file:
        path: /etc/openstack
        state: directory
        owner: slurm # TODO: check this works for rebuild too
        group: slurm
        mode: u=rX,go=
    - name: Copy out clouds.yaml
      copy:
        src: "{{ openhpc_rebuild_clouds }}" # TODO: name is wrong really!
        dest: /etc/openstack/clouds.yaml
        mode: u=r,go=
        owner: slurm
        group: slurm
    - name: Setup Python/Slurm tools
      include_role:
        name: stackhpc.slurm_openstack_tools.pytools
    - name: Configure autoscale programs and parameters
      include_role:
        name: autoscale
      when: "'autoscale' in group_names"
    - name: Configure rebuild programs and parameters
      include_role:
        name: rebuild

- name: Setup slurm
  hosts: openhpc
  become: yes
  tags:
    - openhpc
  tasks:
    # - name: Add CentOS 8.3 Vault repo for OpenHPC hwloc dependency
    #   # NB: REMOVE THIS once OpenHPC works on CentOS 8.4
    #   yum_repository:
    #     name: vault
    #     file: CentOS-Linux-Vault8.3
    #     description:  CentOS 8.3 packages from Vault
    #     baseurl: https://vault.centos.org/8.3.2011/BaseOS/$basearch/os/
    #     gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
    - import_role:
        name: stackhpc.openhpc

- name: Set locked memory limits on user-facing nodes
  hosts:
    - compute
    - login
  become: yes
  tags:
    - openhpc
  tasks:
    - name: set memory limits
      lineinfile:
        path: /etc/security/limits.conf
        regexp: '\* soft memlock unlimited'
        line: "* soft memlock unlimited"

- name: Block ssh to compute nodes for non-privileged users without running jobs
  hosts: compute
  become: yes
  tags:
    - openhpc
  tasks:
    - name: Configure sshd pam module
      blockinfile:
        path: /etc/pam.d/sshd
        insertafter: 'account\s+required\s+pam_nologin.so'
        block: |
          account    sufficient   pam_access.so
          account    required     pam_slurm.so
    - name: Configure login access control
      blockinfile:
        path: /etc/security/access.conf
        block: |
          +:wheel:ALL
          +:{{ ansible_user }}:ALL
          -:ALL:ALL
      # vagrant uses (deprecated) ansible_ssh_user
