---

- name: Setup DB
  hosts: mysql
  become: true
  tags:
    - mysql
  tasks:
    - include_role:
        name:  geerlingguy.mysql

- name: Setup slurm
  hosts: openhpc
  become: yes
  tags:
    - openhpc
  tasks:
   - import_role:
        name: stackhpc.openhpc
