---

- name: Setup DB
  hosts: mysql
  become: true
  tags:
    - mysql
  tasks:
    - include_role:
        name:  geerlingguy.mysql

- name: Setup slurm
  hosts: openhpc
  become: yes
  tags:
    - openhpc
  tasks:
    # - name: Add CentOS 8.3 Vault repo for OpenHPC hwloc dependency
    #   # NB: REMOVE THIS once OpenHPC works on CentOS 8.4
    #   yum_repository:
    #     name: vault
    #     file: CentOS-Linux-Vault8.3
    #     description:  CentOS 8.3 packages from Vault
    #     baseurl: https://vault.centos.org/8.3.2011/BaseOS/$basearch/os/
    #     gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
    - import_role:
        name: stackhpc.openhpc

- name: Setup slurm-driven reimage
  hosts: rebuild
  become: yes
  tags:
    - rebuild
  tasks:
    - import_role:
        name: stackhpc.slurm_openstack_tools.rebuild

- name: Setup autoscaling suspend/resume programs
  # has to happen *after* slurm user has been created
  hosts: autoscale # this is the *controller*
  become: yes
  tags:
    - autoscale
  tasks:
- name: Configure autoscale
  hosts: autoscale
  become: yes
  tags:
    - autoscale
  tasks:
    - name: Create /etc/openstack
      file:
        path: /etc/openstack
        state: directory
        owner: slurm
        group: slurm
        mode: '0500'
    - name: Copy out clouds.yaml
      copy:
        src: "{{ autoscale_clouds }}"
        dest: /etc/openstack/clouds.yaml
        owner: slurm
        group: slurm
        mode: '0400'
    - name: Setup slurm tools (to get venv)
      include_role:
        name: stackhpc.slurm_openstack_tools.pytools
    - name: Create SuspendProgram
      template:
        src: suspend.py.j2
        dest: /opt/slurm-tools/bin/suspend
        owner: slurm
        group: slurm
        mode: u=rwx,go=
      tags: suspend
    - name: Create ResumeProgram
      template:
        src: resume.py.j2
        dest: /opt/slurm-tools/bin/resume
        owner: slurm
        group: slurm
        mode: u=rwx,go=
      tags: resume
    - name: Add Resume/SuspendProgram parameters
      community.general.ini_file:
        path: /etc/slurm/slurm.conf
        option: "{{ item.key }}"
        section: null
        value: "{{ item.value }}"
        no_extra_spaces: true
        create: no
      loop: "{{ {'SuspendProgram':'/opt/slurm-tools/bin/suspend', 'ResumeProgram':'/opt/slurm-tools/bin/resume'} | dict2items }}" # TODO: fixme: hijacking slurm-tools
    - name: Reconfigure slurm
      command:
        cmd: scontrol reconfigure

- name: Set locked memory limits on user-facing nodes
  hosts:
    - compute
    - login
  become: yes
  tags:
    - openhpc
  tasks:
    - name: set memory limits
      lineinfile:
        path: /etc/security/limits.conf
        regexp: '\* soft memlock unlimited'
        line: "* soft memlock unlimited"

- name: Block ssh to compute nodes for non-privileged users without running jobs
  hosts: compute
  become: yes
  tags:
    - openhpc
  tasks:
    - name: Configure sshd pam module
      blockinfile:
        path: /etc/pam.d/sshd
        insertafter: 'account\s+required\s+pam_nologin.so'
        block: |
          account    sufficient   pam_access.so
          account    required     pam_slurm.so
    - name: Configure login access control
      blockinfile:
        path: /etc/security/access.conf
        block: |
          +:wheel:ALL
          +:{{ ansible_user }}:ALL
          -:ALL:ALL
      # vagrant uses (deprecated) ansible_ssh_user
