---

- name: Setup DB
  hosts: mysql
  become: true
  tags:
    - mysql
  tasks:
    - include_role:
        name:  geerlingguy.mysql

- name: Setup slurm
  hosts: openhpc
  become: yes
  tags:
    - openhpc
  tasks:
    - import_role:
        name: stackhpc.openhpc
    - name: set memory limits
      lineinfile:
        path: /etc/security/limits.conf
        regexp: '\* soft memlock unlimited'
        line: "* soft memlock unlimited"
      when: "'control' not in group_names"
