---

# Fail early if configuration is invalid

- name: Validate podman configuration
  hosts: podman
  tags: podman
  tasks:
    - import_role:
        name: podman
        tasks_from: validate.yml
      tags: validate

- name: Validate filebeat configuration
  hosts: filebeat
  tags: filebeat
  tasks:
    - import_role:
        name: filebeat
        tasks_from: validate.yml
      tags: validate

- name: Validate kibana configuration
  hosts: kibana
  tags: kibana
  tasks:
    - import_role:
        name: kibana
        tasks_from: validate.yml
      tags: validate

- name: Validate opendistro configuration
  hosts: opendistro
  tags: opendistro
  tasks:
    - import_role:
        name: opendistro
        tasks_from: validate.yml
      tags: validate

- name: Validate rebuild configuration
  hosts: rebuild
  gather_facts: false
  tags: rebuild
  tasks:
    - import_role:
        name: stackhpc.slurm_openstack_tools.rebuild
        tasks_from: validate.yml
      tags: validate

- name: Validate freeipa configuration
  hosts:
    - ipaserver
    - ipareplicas
    - ipaclients
  gather_facts: false
  tags:
    - ipaserver
    - ipareplicas
    - ipaclients
  tasks:
    - assert:
        that: "{{ item is defined }}"
        fail_msg: "variable {{ item }} has not be defined"
      loop:
        - ipaadmin_password
        - ipadm_password
        - ipaserver_domain
        - ipaserver_realm
      run_once: true
