# Skip plotting pingpong as matplotlib not in runner environment
hpctests_pingpong_plot: false

# In Azimuth, the Ansible controller is an ephemeral pod, so all that matters is that
# this is a location that is writable by the container user
hpctests_outdir: "{{ playbook_dir }}/.tmp/hpctests"
