---
# sync_slurm_allocations vars
sync_slurm_allocations_clustername: "vtest"
slurm_sync_allocations_log_file: "sync_slurm_accounting_vtest.log"


#slurm_sync_allocations_log_path: "/var/log"
# slurm_sync_allocations_vault_file: "vault"
# slurm_sync_allocations_vault_secret_file: "sync_slurm_allocations_secret.yml"

#slurm_sync_allocations_log_path: "/var/log"
#slurm_sync_allocations_slurm_path: "/usr/sbin"

#slurm_sync_allocations_install_path: "/nopt/{{sync_slurm_allocations_clustername}}/lex/slurm_sync_allocations"

