vermilion_cluster_name: vtest
vermilion_cluster_name_prefix: vtest
NREL_RELEASEVER: "9.2"

#ceph.yml
os_manila_mount_ceph_version: pacific

#https://mirrors.hpc.nrel.gov/rocky/9.2/extras/x86_64/os/Packages/c/centos-release-ceph-pacific-1.0-2.el9.noarch.rpm

# sync_slurm_allocations vars
slurm_lex_accounting_dev: False
slurm_lex_accounting_clustername: "{{ vermilion_cluster_name_prefix }}"

sync_slurm_allocations_clustername: "{{ vermilion_cluster_name_prefix }}"
slurm_sync_allocations_log_file: "sync_slurm_accounting_{{ vermilion_cluster_name_prefix }}.log"
