- name: Install sssd packages
  dnf:
    name: "{{ sssd_packages + sssd_ldap_packages if (sssd_install_ldap | bool) else [] }}"

- name: Control if sssd should start on boot
  # Needs to be done here to prevent starting after image build, is enabled by default
  systemd:
    name: sssd
    enabled: "{{ sssd_enabled | bool }}"
