galaxy_info:
  author: Kurt Bendl
  description: Fixes weird missing SAN error from ldap that causes ipa-client-install to fail.
  company: NREL

  # issue_tracker_url: http://example.com/issue/tracker

  license: GPL-2.0-or-later

  min_ansible_version: 2.10

  platforms:
  - name: EL
    versions:
    - 8

  - name: Debian
    versions:
    - 10
    - 11

  - name: Ubuntu
    versions:
    - 20.04

  galaxy_tags:
    - IPA
    - FreeIPA
    - Rocky
    - SAN
    - crt
    - ipa-client-install

dependencies: []
