---
# tasks file for vermilion_ldap_client

- name: "install required packages"
  yum:
    name: "{{ item }}"
  loop:
    - openldap-clients
    - sssd
    - sssd-ldap
    - oddjob-mkhomedir
    - openssl-perl

- name: "install sssd.conf to use NREL's IPA"
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600

- name: "configure LDAP to use IPA"
  template:
    src: ldap.conf.j2
    dest: /etc/openldap/ldap.conf
    owner: root
    group: root
    mode: 0644

- name: "prep system to use ldap configs"
  shell: |
      authselect select sssd with-mkhomedir --force
      openssl rehash /etc/openldap/certs
  register: sh_output

- debug: msg="{{ sh_output }}"

- name: "Update the sshd_conf so password/ldap auth will work"
  copy:
    src: sshd_conf
    dest: /etc/ssh/sshd_conf
    owner: root
    group: root
    mode: 0644

- name: "enable all the things"
  systemd:
    state: restarted
    enabled: true
    daemon_reload: yes
    name: "{{ item }}"
  loop:
    - sssd
    - oddjobd
    - sshd

# /etc/pki/ca-trust/source/anchors/ca.crt
# update-ca-trust
