- hosts: localhost
  become: true
  vars:
    os_metadata: "{{ lookup('url', 'http://169.254.169.254/openstack/latest/meta_data.json') | from_json }}"
    k3s_token: "{{ os_metadata.meta.k3s_token }}"
    k3s_server_name: "{{ os_metadata.meta.k3s_server }}"
  tasks:
    - name: Add the token for joining the cluster to the environment
      no_log: true # avoid logging the server token
      ansible.builtin.lineinfile:
        path: "/etc/systemd/system/k3s-agent.service.env"
        line: "{{ item }}"
      with_items:
        - "K3S_TOKEN={{ k3s_token }}"
        - "K3S_URL=https://{{ k3s_server_name }}:6443"
    - name: Start k3s service
      ansible.builtin.systemd:
        name: k3s-agent
        daemon_reload: true
        state: started
        enabled: true
