openhpc_rebuild_clouds: "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/inventory/group_vars/rebuild/clouds.yaml"

openhpc_packages_extra: "{{ openhpc_packages_extra_nrel | reject('match', '.*-impi-') }}" # don't have intel compilers available

openhpc_slurm_partitions:
  - name: "sm"
    default: NO
    maxtime: "1-0" # 1 days 0 hours
  - name: "ty"
    default: YES
    maxtime: "1-0" # 1 days 0 hours
